### ISSUE TITLE
Investigate tenant creation issue on demo

### ISSUE THREAD

**Issue by aprilrieger** [scientist-softserv/palni-palci#385]
# Summary
1. when creating a tenant I see an error that my name and cname have already been taken. (Logs below)
2. Even when you check to make sure the name is for sure not taken it errors.
3. You go back to the proprietor accounts show page I see it did make my tenant
4. I log into that tenant and I am not an admin, I can tell because the sidebar does not show me the typical admin sidebar.
5. I then have to go back to the proprietor account manage page and add my user as an admin
6. I then go back to the tenant and have an admin sidebar BUT it doesnt show the Analytics menu item: https://github.com/samvera/hyrax/blob/94cd8e0d48991e0acdeccbbddef29749beaeae87/app/views/hyrax/dashboard/sidebar/_activity.html.erb#L36
7. I check my user and my user does not have the ability `<% if current_ability.can_create_any_work? %>`
8. So I look at the logs and notice it errors on the step of creating an admin set, and assume that is the reason why :shrugs: my assumption without digging deeper.

![Image](https://user-images.githubusercontent.com/63515648/211643405-898e841b-5cb1-41c5-8181-70b6da4314ab.png)

Videos:
User getting error that tenant name and cname have already been taken: https://share.getcloudapp.com/GGuJKKAE

User not getting added as primary admin upon creation && the users current_ability.can_create_any_work? == 'false' && the default AdminSet is not getting created: https://share.getcloudapp.com/12uRLLJE

Hyrax default admin dashboard/sidebar/activity/gogle_analytics tab: https://github.com/samvera/hyrax/blob/94cd8e0d48991e0acdeccbbddef29749beaeae87/app/views/hyrax/dashboard/sidebar/_activity.html.erb#L36

`<% if current_ability.can_create_any_work? %>`

Logs:
```yaml
#1] DEBUG -- : [f84fd275e7ff0204d6e7c630ce3a8769]   [1m[36mHyrax::CollectionTypeParticipant Create (0.8ms)[0m  [1m[32mINSERT INTO "collection_type_participants" ("hyrax_collection_type_id", "agent_type", "agent_id", "access", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5, $6) RETURNING "id"[0m  [["hyrax_collection_type_id", 2], ["agent_type", "group"], ["agent_id", "admin"], ["access", "manage"], ["created_at", "2023-01-10 19:04:43.131909"], ["updated_at", "2023-01-10 19:04:43.131909"]]
D, [2023-01-10T19:04:43.135095 #1] DEBUG -- : [f84fd275e7ff0204d6e7c630ce3a8769]   [1m[35m (1.6ms)[0m  [1m[35mCOMMIT[0m
D, [2023-01-10T19:04:43.136001 #1] DEBUG -- : [f84fd275e7ff0204d6e7c630ce3a8769]   [1m[35m (0.7ms)[0m  [1m[35mBEGIN[0m
D, [2023-01-10T19:04:43.137642 #1] DEBUG -- : [f84fd275e7ff0204d6e7c630ce3a8769]   [1m[36mHyrax::CollectionTypeParticipant Create (0.9ms)[0m  [1m[32mINSERT INTO "collection_type_participants" ("hyrax_collection_type_id", "agent_type", "agent_id", "access", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5, $6) RETURNING "id"[0m  [["hyrax_collection_type_id", 2], ["agent_type", "group"], ["agent_id", "admin"], ["access", "create"], ["created_at", "2023-01-10 19:04:43.136211"], ["updated_at", "2023-01-10 19:04:43.136211"]]
D, [2023-01-10T19:04:43.139270 #1] DEBUG -- : [f84fd275e7ff0204d6e7c630ce3a8769]   [1m[35m (1.4ms)[0m  [1m[35mCOMMIT[0m
DEPRECATION WARNING: You are using deprecated behavior which will be removed from the next major or minor release. (called from create_defaults at /app/samvera/hyrax-webapp/app/services/create_account.rb:49)
D, [2023-01-10T19:04:43.144376 #1] DEBUG -- : [f84fd275e7ff0204d6e7c630ce3a8769]   [1m[36mHyrax::DefaultAdministrativeSet Load (0.8ms)[0m  [1m[34mSELECT  "hyrax_default_administrative_set".* FROM "hyrax_default_administrative_set" ORDER BY "hyrax_default_administrative_set"."id" ASC LIMIT $1[0m  [["LIMIT", 1]]
I, [2023-01-10T19:05:24.077495 #1]  INFO -- : [ce876f13619573a0438d841d1b2680eb] Started GET "/sftp-config.json" for 10.0.6.57 at 2023-01-10 19:05:24 +0000
D, [2023-01-10T19:05:24.171741 #1] DEBUG -- : [ce876f13619573a0438d841d1b2680eb]   [1m[36mAccount Load (1.6ms)[0m  [1m[34mSELECT  "public"."accounts".* FROM "public"."accounts" INNER JOIN "public"."domain_names" ON "public"."domain_names"."account_id" = "public"."accounts"."id" WHERE "domain_names"."is_active" = $1 AND "domain_names"."cname" = $2 LIMIT $3[0m  [["is_active", true], ["cname", "commons-archive.org"], ["LIMIT", 1]]
D, [2023-01-10T19:05:24.172694 #1] DEBUG -- : [ce876f13619573a0438d841d1b2680eb] User excluded error: #<ActionController::RoutingError: No route matches [GET] "/sftp-config.json">
F, [2023-01-10T19:05:24.173087 #1] FATAL -- : [ce876f13619573a0438d841d1b2680eb]   
F, [2023-01-10T19:05:24.173169 #1] FATAL -- : [ce876f13619573a0438d841d1b2680eb] ActionController::RoutingError (No route matches [GET] "/sftp-config.json"):
F, [2023-01-10T19:05:24.173202 #1] FATAL -- : [ce876f13619573a0438d841d1b2680eb]   
F, [2023-01-10T19:05:24.173233 #1] FATAL -- : [ce876f13619573a0438d841d1b2680eb] app/middleware/no_cache_middleware.rb:13:in `call'
10.0.5.28, 10.0.5.221 - - [10/Jan/2023:19:05:24 +0000] "GET /404 HTTP/1.0" 404 1564 0.0973
I, [2023-01-10T19:05:32.338856 #1]  INFO -- : [d167be968b7d7379f13556285081af1e] Started GET "/sftp-config.json" for 10.0.6.57 at 2023-01-10 19:05:32 +0000
D, [2023-01-10T19:05:32.342099 #1] DEBUG -- : [d167be968b7d7379f13556285081af1e]   [1m[36mAccount Load (1.1ms)[0m  [1m[34mSELECT  "public"."accounts".* FROM "public"."accounts" INNER JOIN "public"."domain_names" ON "public"."domain_names"."account_id" = "public"."accounts"."id" WHERE "domain_names"."is_active" = $1 AND "domain_names"."cname" = $2 LIMIT $3[0m  [["is_active", true], ["cname", "commons-archive.org"], ["LIMIT", 1]]
D, [2023-01-10T19:05:32.342861 #1] DEBUG -- : [d167be968b7d7379f13556285081af1e] User excluded error: #<ActionController::RoutingError: No route matches [GET] "/sftp-config.json">
F, [2023-01-10T19:05:32.343184 #1] FATAL -- : [d167be968b7d7379f13556285081af1e]   
F, [2023-01-10T19:05:32.343221 #1] FATAL -- : [d167be968b7d7379f13556285081af1e] ActionController::RoutingError (No route matches [GET] "/sftp-config.json"):
F, [2023-01-10T19:05:32.343240 #1] FATAL -- : [d167be968b7d7379f13556285081af1e]   
F, [2023-01-10T19:05:32.343269 #1] FATAL -- : [d167be968b7d7379f13556285081af1e] app/middleware/no_cache_middleware.rb:13:in `call'
10.0.5.211, 10.0.5.221 - - [10/Jan/2023:19:05:32 +0000] "GET /404 HTTP/1.0" 404 1564 0.0057
D, [2023-01-10T19:05:43.219475 #1] DEBUG -- : [f84fd275e7ff0204d6e7c630ce3a8769]   [1m[36mAccount Load (0.9ms)[0m  [1m[34mSELECT  "public"."accounts".* FROM "public"."accounts" WHERE "public"."accounts"."tenant" = $1 LIMIT $2[0m  [["tenant", "public"], ["LIMIT", 1]]
I, [2023-01-10T19:05:43.220217 #1]  INFO -- : [f84fd275e7ff0204d6e7c630ce3a8769] Completed 500 Internal Server Error in 63692ms (ActiveRecord: 1832.6ms)
I, [2023-01-10T19:05:43.263974 #1]  INFO -- : [f84fd275e7ff0204d6e7c630ce3a8769] Sending event 5500a1adf22347e0b5d63ab5b9ab5de5 to Sentry
F, [2023-01-10T19:05:43.394270 #1] FATAL -- : [f84fd275e7ff0204d6e7c630ce3a8769]   
F, [2023-01-10T19:05:43.394372 #1] FATAL -- : [f84fd275e7ff0204d6e7c630ce3a8769] Faraday::TimeoutError (Net::ReadTimeout with #<TCPSocket:(closed)>):
F, [2023-01-10T19:05:43.394412 #1] FATAL -- : [f84fd275e7ff0204d6e7c630ce3a8769]   
F, [2023-01-10T19:05:43.394446 #1] FATAL -- : [f84fd275e7ff0204d6e7c630ce3a8769] app/services/create_account.rb:49:in `create_defaults'
[f84fd275e7ff0204d6e7c630ce3a8769] app/services/create_account.rb:33:in `block (2 levels) in create_tenant'
[f84fd275e7ff0204d6e7c630ce3a8769] app/models/account.rb:108:in `switch'
[f84fd275e7ff0204d6e7c630ce3a8769] app/services/create_account.rb:32:in `block in create_tenant'
[f84fd275e7ff0204d6e7c630ce3a8769] app/services/create_account.rb:30:in `create_tenant'
[f84fd275e7ff0204d6e7c630ce3a8769] app/services/create_account.rb:24:in `create_external_resources'
[f84fd275e7ff0204d6e7c630ce3a8769] app/services/create_account.rb:16:in `save'
[f84fd275e7ff0204d6e7c630ce3a8769] app/controllers/proprietor/accounts_controller.rb:50:in `block in create'
[f84fd275e7ff0204d6e7c630ce3a8769] app/controllers/proprietor/accounts_controller.rb:48:in `create'
[f84fd275e7ff0204d6e7c630ce3a8769] app/middleware/no_cache_middleware.rb:13:in `call'
10.0.6.67, 10.0.5.221 - - [10/Jan/2023:19:05:43 +0000] "POST /500?locale=en HTTP/1.0" 500 5588 63.8724
```

**Comment by bkiahstroud** [comment]
### NOTE

This does not seem to be an issue in base Hyku. It's possible this may have been fixed in this Hyku PR (https://github.com/samvera/hyku/pull/1859), so it's worth checking again after those changes get backported into pals

**Comment by crisr15** [comment]
check env in pod.

**Comment by bkiahstroud** [comment]
Summarized input from @orangewolf -- 

> Solr/fedora urls could be right on every individual tenant, but wrong in the global scope. Tenants that get part of the way through the creation process, but fail before the end, cause really weird behavior. This could be that

**Comment by bkiahstroud** [comment]
This may be resolved by #382, please test

**Comment by crisr15** [comment]
To Test create new account   Make sure an admin set exists and you can add work.  Then tenant can be deleted.

**Comment by crisr15** [comment]
Created new test account.  Admin set was created and new work could be created.  


![Image](https://user-images.githubusercontent.com/11359350/224814769-3553f53e-0a4e-4a39-b525-5b967c4374dc.png)
